// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// load_block_file
std::vector<arma::umat> load_block_file(const std::string& block_file);
RcppExport SEXP _CHESS_load_block_file(SEXP block_fileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type block_file(block_fileSEXP);
    rcpp_result_gen = Rcpp::wrap(load_block_file(block_file));
    return rcpp_result_gen;
END_RCPP
}
// test_blocks
List test_blocks(arma::ivec bp, arma::ivec chr, std::string block_file);
RcppExport SEXP _CHESS_test_blocks(SEXP bpSEXP, SEXP chrSEXP, SEXP block_fileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::ivec >::type bp(bpSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type chr(chrSEXP);
    Rcpp::traits::input_parameter< std::string >::type block_file(block_fileSEXP);
    rcpp_result_gen = Rcpp::wrap(test_blocks(bp, chr, block_file));
    return rcpp_result_gen;
END_RCPP
}
// std_setdiff
arma::ivec std_setdiff(arma::ivec& x, arma::ivec& y);
RcppExport SEXP _CHESS_std_setdiff(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::ivec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::ivec& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(std_setdiff(x, y));
    return rcpp_result_gen;
END_RCPP
}
// LDclump
arma::ivec LDclump(arma::mat& R, double ld_r2_thresh);
RcppExport SEXP _CHESS_LDclump(SEXP RSEXP, SEXP ld_r2_threshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< double >::type ld_r2_thresh(ld_r2_threshSEXP);
    rcpp_result_gen = Rcpp::wrap(LDclump(R, ld_r2_thresh));
    return rcpp_result_gen;
END_RCPP
}
// Cal_blockR
List Cal_blockR(arma::ivec& bp, arma::ivec& chr, arma::uvec& avbIndex, arma::uvec& idx4panel, std::string block_file, std::string stringname3, double ld_r2_thresh, int coreNum, double lam);
RcppExport SEXP _CHESS_Cal_blockR(SEXP bpSEXP, SEXP chrSEXP, SEXP avbIndexSEXP, SEXP idx4panelSEXP, SEXP block_fileSEXP, SEXP stringname3SEXP, SEXP ld_r2_threshSEXP, SEXP coreNumSEXP, SEXP lamSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::ivec& >::type bp(bpSEXP);
    Rcpp::traits::input_parameter< arma::ivec& >::type chr(chrSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type avbIndex(avbIndexSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type idx4panel(idx4panelSEXP);
    Rcpp::traits::input_parameter< std::string >::type block_file(block_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type stringname3(stringname3SEXP);
    Rcpp::traits::input_parameter< double >::type ld_r2_thresh(ld_r2_threshSEXP);
    Rcpp::traits::input_parameter< int >::type coreNum(coreNumSEXP);
    Rcpp::traits::input_parameter< double >::type lam(lamSEXP);
    rcpp_result_gen = Rcpp::wrap(Cal_blockR(bp, chr, avbIndex, idx4panel, block_file, stringname3, ld_r2_thresh, coreNum, lam));
    return rcpp_result_gen;
END_RCPP
}
// Cal_block_Rmatrix
List Cal_block_Rmatrix(arma::ivec& bp, arma::ivec& chr, arma::uvec& avbIndex, arma::uvec& idx4panel, std::string block_file, std::string stringname3, double ld_r2_thresh, int coreNum, double lam);
RcppExport SEXP _CHESS_Cal_block_Rmatrix(SEXP bpSEXP, SEXP chrSEXP, SEXP avbIndexSEXP, SEXP idx4panelSEXP, SEXP block_fileSEXP, SEXP stringname3SEXP, SEXP ld_r2_threshSEXP, SEXP coreNumSEXP, SEXP lamSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::ivec& >::type bp(bpSEXP);
    Rcpp::traits::input_parameter< arma::ivec& >::type chr(chrSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type avbIndex(avbIndexSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type idx4panel(idx4panelSEXP);
    Rcpp::traits::input_parameter< std::string >::type block_file(block_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type stringname3(stringname3SEXP);
    Rcpp::traits::input_parameter< double >::type ld_r2_thresh(ld_r2_threshSEXP);
    Rcpp::traits::input_parameter< int >::type coreNum(coreNumSEXP);
    Rcpp::traits::input_parameter< double >::type lam(lamSEXP);
    rcpp_result_gen = Rcpp::wrap(Cal_block_Rmatrix(bp, chr, avbIndex, idx4panel, block_file, stringname3, ld_r2_thresh, coreNum, lam));
    return rcpp_result_gen;
END_RCPP
}
// Cal_blockinf
List Cal_blockinf(arma::ivec& bp, arma::ivec& chr, std::string block_file);
RcppExport SEXP _CHESS_Cal_blockinf(SEXP bpSEXP, SEXP chrSEXP, SEXP block_fileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::ivec& >::type bp(bpSEXP);
    Rcpp::traits::input_parameter< arma::ivec& >::type chr(chrSEXP);
    Rcpp::traits::input_parameter< std::string >::type block_file(block_fileSEXP);
    rcpp_result_gen = Rcpp::wrap(Cal_blockinf(bp, chr, block_file));
    return rcpp_result_gen;
END_RCPP
}
// IndepSummary
Rcpp::List IndepSummary(arma::ivec& bp, arma::ivec& chr, arma::uvec& avbIndex, std::string& block_file, std::string stringname3, arma::vec& bh1, arma::vec& bh2, arma::vec& se1, arma::vec& se2, int coreNum, double lam, const double& ld_r2_thresh);
RcppExport SEXP _CHESS_IndepSummary(SEXP bpSEXP, SEXP chrSEXP, SEXP avbIndexSEXP, SEXP block_fileSEXP, SEXP stringname3SEXP, SEXP bh1SEXP, SEXP bh2SEXP, SEXP se1SEXP, SEXP se2SEXP, SEXP coreNumSEXP, SEXP lamSEXP, SEXP ld_r2_threshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::ivec& >::type bp(bpSEXP);
    Rcpp::traits::input_parameter< arma::ivec& >::type chr(chrSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type avbIndex(avbIndexSEXP);
    Rcpp::traits::input_parameter< std::string& >::type block_file(block_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type stringname3(stringname3SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type bh1(bh1SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type bh2(bh2SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type se1(se1SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type se2(se2SEXP);
    Rcpp::traits::input_parameter< int >::type coreNum(coreNumSEXP);
    Rcpp::traits::input_parameter< double >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< const double& >::type ld_r2_thresh(ld_r2_threshSEXP);
    rcpp_result_gen = Rcpp::wrap(IndepSummary(bp, chr, avbIndex, block_file, stringname3, bh1, bh2, se1, se2, coreNum, lam, ld_r2_thresh));
    return rcpp_result_gen;
END_RCPP
}
// testR
double testR(double rho, int n);
RcppExport SEXP _CHESS_testR(SEXP rhoSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(testR(rho, n));
    return rcpp_result_gen;
END_RCPP
}
// comb
arma::imat comb(int p);
RcppExport SEXP _CHESS_comb(SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(comb(p));
    return rcpp_result_gen;
END_RCPP
}
// Mat2Vec
arma::vec Mat2Vec(arma::mat R);
RcppExport SEXP _CHESS_Mat2Vec(SEXP RSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type R(RSEXP);
    rcpp_result_gen = Rcpp::wrap(Mat2Vec(R));
    return rcpp_result_gen;
END_RCPP
}
// Vec2Mat
arma::mat Vec2Mat(arma::vec RV, int p1);
RcppExport SEXP _CHESS_Vec2Mat(SEXP RVSEXP, SEXP p1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type RV(RVSEXP);
    Rcpp::traits::input_parameter< int >::type p1(p1SEXP);
    rcpp_result_gen = Rcpp::wrap(Vec2Mat(RV, p1));
    return rcpp_result_gen;
END_RCPP
}
// Cal_block_Rvec
List Cal_block_Rvec(arma::ivec& bp, arma::ivec& chr, arma::uvec& avbIndex, std::string block_file, std::string stringname3, int coreNum, double lam);
RcppExport SEXP _CHESS_Cal_block_Rvec(SEXP bpSEXP, SEXP chrSEXP, SEXP avbIndexSEXP, SEXP block_fileSEXP, SEXP stringname3SEXP, SEXP coreNumSEXP, SEXP lamSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::ivec& >::type bp(bpSEXP);
    Rcpp::traits::input_parameter< arma::ivec& >::type chr(chrSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type avbIndex(avbIndexSEXP);
    Rcpp::traits::input_parameter< std::string >::type block_file(block_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type stringname3(stringname3SEXP);
    Rcpp::traits::input_parameter< int >::type coreNum(coreNumSEXP);
    Rcpp::traits::input_parameter< double >::type lam(lamSEXP);
    rcpp_result_gen = Rcpp::wrap(Cal_block_Rvec(bp, chr, avbIndex, block_file, stringname3, coreNum, lam));
    return rcpp_result_gen;
END_RCPP
}
// MRGEI_Gam3seo
List MRGEI_Gam3seo(arma::vec& gammah1, arma::vec& gammah3, arma::vec& Gammah1, arma::vec& Gammah3, arma::vec& se1, arma::vec& se2, arma::vec& se3, arma::vec& se4, arma::mat& R, double& rho_1, double& rho_2);
RcppExport SEXP _CHESS_MRGEI_Gam3seo(SEXP gammah1SEXP, SEXP gammah3SEXP, SEXP Gammah1SEXP, SEXP Gammah3SEXP, SEXP se1SEXP, SEXP se2SEXP, SEXP se3SEXP, SEXP se4SEXP, SEXP RSEXP, SEXP rho_1SEXP, SEXP rho_2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type gammah1(gammah1SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type gammah3(gammah3SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type Gammah1(Gammah1SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type Gammah3(Gammah3SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type se1(se1SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type se2(se2SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type se3(se3SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type se4(se4SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< double& >::type rho_1(rho_1SEXP);
    Rcpp::traits::input_parameter< double& >::type rho_2(rho_2SEXP);
    rcpp_result_gen = Rcpp::wrap(MRGEI_Gam3seo(gammah1, gammah3, Gammah1, Gammah3, se1, se2, se3, se4, R, rho_1, rho_2));
    return rcpp_result_gen;
END_RCPP
}
// getLineNum
int getLineNum(std::string filename);
RcppExport SEXP _CHESS_getLineNum(SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    rcpp_result_gen = Rcpp::wrap(getLineNum(filename));
    return rcpp_result_gen;
END_RCPP
}
// ReadSNPinfo
Rcpp::List ReadSNPinfo(std::string stringname, IntegerVector A1, IntegerVector A2, CharacterVector rsname, IntegerVector chr, IntegerVector bp, NumericVector morgan, int N);
RcppExport SEXP _CHESS_ReadSNPinfo(SEXP stringnameSEXP, SEXP A1SEXP, SEXP A2SEXP, SEXP rsnameSEXP, SEXP chrSEXP, SEXP bpSEXP, SEXP morganSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type stringname(stringnameSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type A1(A1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type A2(A2SEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type rsname(rsnameSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type chr(chrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type bp(bpSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type morgan(morganSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(ReadSNPinfo(stringname, A1, A2, rsname, chr, bp, morgan, N));
    return rcpp_result_gen;
END_RCPP
}
// Read_summarystat
void Read_summarystat(std::string stringname, IntegerVector SA1, IntegerVector SA2, CharacterVector rsname, NumericVector betah, NumericVector s2, NumericVector pvalue, IntegerVector chr, IntegerVector bp, int N);
RcppExport SEXP _CHESS_Read_summarystat(SEXP stringnameSEXP, SEXP SA1SEXP, SEXP SA2SEXP, SEXP rsnameSEXP, SEXP betahSEXP, SEXP s2SEXP, SEXP pvalueSEXP, SEXP chrSEXP, SEXP bpSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type stringname(stringnameSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type SA1(SA1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type SA2(SA2SEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type rsname(rsnameSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type betah(betahSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type s2(s2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pvalue(pvalueSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type chr(chrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type bp(bpSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Read_summarystat(stringname, SA1, SA2, rsname, betah, s2, pvalue, chr, bp, N);
    return R_NilValue;
END_RCPP
}
// select
CharacterVector select(CharacterVector vec_, NumericVector idx_);
RcppExport SEXP _CHESS_select(SEXP vec_SEXP, SEXP idx_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type vec_(vec_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type idx_(idx_SEXP);
    rcpp_result_gen = Rcpp::wrap(select(vec_, idx_));
    return rcpp_result_gen;
END_RCPP
}
// matchsnp
Rcpp::List matchsnp(std::string stringname1, std::string stringname2, std::string stringname3, bool matchExp);
RcppExport SEXP _CHESS_matchsnp(SEXP stringname1SEXP, SEXP stringname2SEXP, SEXP stringname3SEXP, SEXP matchExpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type stringname1(stringname1SEXP);
    Rcpp::traits::input_parameter< std::string >::type stringname2(stringname2SEXP);
    Rcpp::traits::input_parameter< std::string >::type stringname3(stringname3SEXP);
    Rcpp::traits::input_parameter< bool >::type matchExp(matchExpSEXP);
    rcpp_result_gen = Rcpp::wrap(matchsnp(stringname1, stringname2, stringname3, matchExp));
    return rcpp_result_gen;
END_RCPP
}
// matchscreen
Rcpp::List matchscreen(std::string screenname, std::string stringname1, std::string stringname2, std::string stringname3, double pva_cutoff, bool matchExp);
RcppExport SEXP _CHESS_matchscreen(SEXP screennameSEXP, SEXP stringname1SEXP, SEXP stringname2SEXP, SEXP stringname3SEXP, SEXP pva_cutoffSEXP, SEXP matchExpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type screenname(screennameSEXP);
    Rcpp::traits::input_parameter< std::string >::type stringname1(stringname1SEXP);
    Rcpp::traits::input_parameter< std::string >::type stringname2(stringname2SEXP);
    Rcpp::traits::input_parameter< std::string >::type stringname3(stringname3SEXP);
    Rcpp::traits::input_parameter< double >::type pva_cutoff(pva_cutoffSEXP);
    Rcpp::traits::input_parameter< bool >::type matchExp(matchExpSEXP);
    rcpp_result_gen = Rcpp::wrap(matchscreen(screenname, stringname1, stringname2, stringname3, pva_cutoff, matchExp));
    return rcpp_result_gen;
END_RCPP
}
// phi
double phi(double x);
RcppExport SEXP _CHESS_phi(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(phi(x));
    return rcpp_result_gen;
END_RCPP
}
// cdfNormal
double cdfNormal(double x, double mean, double sd);
RcppExport SEXP _CHESS_cdfNormal(SEXP xSEXP, SEXP meanSEXP, SEXP sdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< double >::type sd(sdSEXP);
    rcpp_result_gen = Rcpp::wrap(cdfNormal(x, mean, sd));
    return rcpp_result_gen;
END_RCPP
}
// MulticdfNormal
arma::vec MulticdfNormal(arma::vec& x);
RcppExport SEXP _CHESS_MulticdfNormal(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(MulticdfNormal(x));
    return rcpp_result_gen;
END_RCPP
}
// multiphi
arma::vec multiphi(arma::vec x);
RcppExport SEXP _CHESS_multiphi(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(multiphi(x));
    return rcpp_result_gen;
END_RCPP
}
// inverseNormal
double inverseNormal(double prob, double mean, double sd);
RcppExport SEXP _CHESS_inverseNormal(SEXP probSEXP, SEXP meanSEXP, SEXP sdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type prob(probSEXP);
    Rcpp::traits::input_parameter< double >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< double >::type sd(sdSEXP);
    rcpp_result_gen = Rcpp::wrap(inverseNormal(prob, mean, sd));
    return rcpp_result_gen;
END_RCPP
}
// MultiinverseNormal
arma::vec MultiinverseNormal(arma::vec& prob);
RcppExport SEXP _CHESS_MultiinverseNormal(SEXP probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type prob(probSEXP);
    rcpp_result_gen = Rcpp::wrap(MultiinverseNormal(prob));
    return rcpp_result_gen;
END_RCPP
}
// MatSum
arma::mat MatSum(arma::vec& y1, arma::vec& y2);
RcppExport SEXP _CHESS_MatSum(SEXP y1SEXP, SEXP y2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type y1(y1SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type y2(y2SEXP);
    rcpp_result_gen = Rcpp::wrap(MatSum(y1, y2));
    return rcpp_result_gen;
END_RCPP
}
// truncEstfun
arma::vec truncEstfun(arma::vec& a, arma::vec& b, arma::vec& x1, arma::vec& x2, int maxIter, int burnin, int thin);
RcppExport SEXP _CHESS_truncEstfun(SEXP aSEXP, SEXP bSEXP, SEXP x1SEXP, SEXP x2SEXP, SEXP maxIterSEXP, SEXP burninSEXP, SEXP thinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< int >::type maxIter(maxIterSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    rcpp_result_gen = Rcpp::wrap(truncEstfun(a, b, x1, x2, maxIter, burnin, thin));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CHESS_load_block_file", (DL_FUNC) &_CHESS_load_block_file, 1},
    {"_CHESS_test_blocks", (DL_FUNC) &_CHESS_test_blocks, 3},
    {"_CHESS_std_setdiff", (DL_FUNC) &_CHESS_std_setdiff, 2},
    {"_CHESS_LDclump", (DL_FUNC) &_CHESS_LDclump, 2},
    {"_CHESS_Cal_blockR", (DL_FUNC) &_CHESS_Cal_blockR, 9},
    {"_CHESS_Cal_block_Rmatrix", (DL_FUNC) &_CHESS_Cal_block_Rmatrix, 9},
    {"_CHESS_Cal_blockinf", (DL_FUNC) &_CHESS_Cal_blockinf, 3},
    {"_CHESS_IndepSummary", (DL_FUNC) &_CHESS_IndepSummary, 12},
    {"_CHESS_testR", (DL_FUNC) &_CHESS_testR, 2},
    {"_CHESS_comb", (DL_FUNC) &_CHESS_comb, 1},
    {"_CHESS_Mat2Vec", (DL_FUNC) &_CHESS_Mat2Vec, 1},
    {"_CHESS_Vec2Mat", (DL_FUNC) &_CHESS_Vec2Mat, 2},
    {"_CHESS_Cal_block_Rvec", (DL_FUNC) &_CHESS_Cal_block_Rvec, 7},
    {"_CHESS_MRGEI_Gam3seo", (DL_FUNC) &_CHESS_MRGEI_Gam3seo, 11},
    {"_CHESS_getLineNum", (DL_FUNC) &_CHESS_getLineNum, 1},
    {"_CHESS_ReadSNPinfo", (DL_FUNC) &_CHESS_ReadSNPinfo, 8},
    {"_CHESS_Read_summarystat", (DL_FUNC) &_CHESS_Read_summarystat, 10},
    {"_CHESS_select", (DL_FUNC) &_CHESS_select, 2},
    {"_CHESS_matchsnp", (DL_FUNC) &_CHESS_matchsnp, 4},
    {"_CHESS_matchscreen", (DL_FUNC) &_CHESS_matchscreen, 6},
    {"_CHESS_phi", (DL_FUNC) &_CHESS_phi, 1},
    {"_CHESS_cdfNormal", (DL_FUNC) &_CHESS_cdfNormal, 3},
    {"_CHESS_MulticdfNormal", (DL_FUNC) &_CHESS_MulticdfNormal, 1},
    {"_CHESS_multiphi", (DL_FUNC) &_CHESS_multiphi, 1},
    {"_CHESS_inverseNormal", (DL_FUNC) &_CHESS_inverseNormal, 3},
    {"_CHESS_MultiinverseNormal", (DL_FUNC) &_CHESS_MultiinverseNormal, 1},
    {"_CHESS_MatSum", (DL_FUNC) &_CHESS_MatSum, 2},
    {"_CHESS_truncEstfun", (DL_FUNC) &_CHESS_truncEstfun, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_CHESS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
