# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

load_block_file <- function(block_file) {
    .Call(`_CHESS_load_block_file`, block_file)
}

test_blocks <- function(bp, chr, block_file) {
    .Call(`_CHESS_test_blocks`, bp, chr, block_file)
}

std_setdiff <- function(x, y) {
    .Call(`_CHESS_std_setdiff`, x, y)
}

LDclump <- function(R, ld_r2_thresh) {
    .Call(`_CHESS_LDclump`, R, ld_r2_thresh)
}

Cal_blockR <- function(bp, chr, avbIndex, idx4panel, block_file, stringname3, ld_r2_thresh, coreNum, lam) {
    .Call(`_CHESS_Cal_blockR`, bp, chr, avbIndex, idx4panel, block_file, stringname3, ld_r2_thresh, coreNum, lam)
}

Cal_block_Rmatrix <- function(bp, chr, avbIndex, idx4panel, block_file, stringname3, ld_r2_thresh, coreNum, lam) {
    .Call(`_CHESS_Cal_block_Rmatrix`, bp, chr, avbIndex, idx4panel, block_file, stringname3, ld_r2_thresh, coreNum, lam)
}

Cal_blockinf <- function(bp, chr, block_file) {
    .Call(`_CHESS_Cal_blockinf`, bp, chr, block_file)
}

IndepSummary <- function(bp, chr, avbIndex, block_file, stringname3, bh1, bh2, se1, se2, coreNum, lam, ld_r2_thresh) {
    .Call(`_CHESS_IndepSummary`, bp, chr, avbIndex, block_file, stringname3, bh1, bh2, se1, se2, coreNum, lam, ld_r2_thresh)
}

testR <- function(rho, n) {
    .Call(`_CHESS_testR`, rho, n)
}

comb <- function(p) {
    .Call(`_CHESS_comb`, p)
}

Mat2Vec <- function(R) {
    .Call(`_CHESS_Mat2Vec`, R)
}

Vec2Mat <- function(RV, p1) {
    .Call(`_CHESS_Vec2Mat`, RV, p1)
}

Cal_block_Rvec <- function(bp, chr, avbIndex, block_file, stringname3, coreNum, lam) {
    .Call(`_CHESS_Cal_block_Rvec`, bp, chr, avbIndex, block_file, stringname3, coreNum, lam)
}

MRGEI_Gam3seo <- function(gammah1, gammah3, Gammah1, Gammah3, se1, se2, se3, se4, R, rho_1, rho_2) {
    .Call(`_CHESS_MRGEI_Gam3seo`, gammah1, gammah3, Gammah1, Gammah3, se1, se2, se3, se4, R, rho_1, rho_2)
}

getLineNum <- function(filename) {
    .Call(`_CHESS_getLineNum`, filename)
}

ReadSNPinfo <- function(stringname, A1, A2, rsname, chr, bp, morgan, N) {
    .Call(`_CHESS_ReadSNPinfo`, stringname, A1, A2, rsname, chr, bp, morgan, N)
}

Read_summarystat <- function(stringname, SA1, SA2, rsname, betah, s2, pvalue, chr, bp, N) {
    invisible(.Call(`_CHESS_Read_summarystat`, stringname, SA1, SA2, rsname, betah, s2, pvalue, chr, bp, N))
}

select <- function(vec_, idx_) {
    .Call(`_CHESS_select`, vec_, idx_)
}

matchsnp <- function(stringname1, stringname2, stringname3, matchExp) {
    .Call(`_CHESS_matchsnp`, stringname1, stringname2, stringname3, matchExp)
}

matchscreen <- function(screenname, stringname1, stringname2, stringname3, pva_cutoff, matchExp = FALSE) {
    .Call(`_CHESS_matchscreen`, screenname, stringname1, stringname2, stringname3, pva_cutoff, matchExp)
}

phi <- function(x) {
    .Call(`_CHESS_phi`, x)
}

cdfNormal <- function(x, mean, sd) {
    .Call(`_CHESS_cdfNormal`, x, mean, sd)
}

MulticdfNormal <- function(x) {
    .Call(`_CHESS_MulticdfNormal`, x)
}

multiphi <- function(x) {
    .Call(`_CHESS_multiphi`, x)
}

inverseNormal <- function(prob, mean, sd) {
    .Call(`_CHESS_inverseNormal`, prob, mean, sd)
}

MultiinverseNormal <- function(prob) {
    .Call(`_CHESS_MultiinverseNormal`, prob)
}

MatSum <- function(y1, y2) {
    .Call(`_CHESS_MatSum`, y1, y2)
}

truncEstfun <- function(a, b, x1, x2, maxIter, burnin, thin) {
    .Call(`_CHESS_truncEstfun`, a, b, x1, x2, maxIter, burnin, thin)
}

